version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: bookclub
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: bookclub
      MYSQL_DATABASE: bookclub
      MYSQL_USER: admin
      MYSQL_PASSWORD: bookclub
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - bookclub

volumes:
  mysql_data:

networks:
  bookclub:
